<Project Sdk="Meadow.Sdk/1.1.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OutputType>Library</OutputType>
    <AssemblyName>App</AssemblyName>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Meadow.ProjectLab\Source\Meadow.ProjectLab\Meadow.ProjectLab.csproj" />
    <ProjectReference Include="..\..\Meadow.Foundation\Source\Meadow.Foundation.Peripherals\mikroBus\CGNSS10\Driver\CGNSS10.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="meadow.config.yaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
